// Comprehensive country-to-currency mapping for all 195+ countries worldwide
// This ensures accurate currency detection regardless of user location

export const COUNTRY_CURRENCY_MAP = {
  // Africa
  'NG': { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', locale: 'en-NG' },
  'ZA': { code: 'ZAR', symbol: 'R', name: 'South African Rand', locale: 'en-ZA' },
  'EG': { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', locale: 'ar-EG' },
  'KE': { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', locale: 'en-KE' },
  'GH': { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi', locale: 'en-GH' },
  'MA': { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham', locale: 'ar-MA' },
  'TN': { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar', locale: 'ar-TN' },
  'DZ': { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', locale: 'ar-DZ' },
  'LY': { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar', locale: 'ar-LY' },
  'AO': { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', locale: 'pt-AO' },
  'BW': { code: 'BWP', symbol: 'P', name: 'Botswana Pula', locale: 'en-BW' },
  'CV': { code: 'CVE', symbol: 'Esc', name: 'Cape Verdean Escudo', locale: 'pt-CV' },
  'CM': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-CM' },
  'TD': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-TD' },
  'CF': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-CF' },
  'CG': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-CG' },
  'CD': { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', locale: 'fr-CD' },
  'DJ': { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', locale: 'fr-DJ' },
  'GQ': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'es-GQ' },
  'ER': { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', locale: 'ti-ER' },
  'SZ': { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', locale: 'en-SZ' },
  'ET': { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', locale: 'am-ET' },
  'GA': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-GA' },
  'GM': { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', locale: 'en-GM' },
  'GN': { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', locale: 'fr-GN' },
  'GW': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'pt-GW' },
  'CI': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-CI' },
  'LS': { code: 'LSL', symbol: 'M', name: 'Lesotho Loti', locale: 'en-LS' },
  'LR': { code: 'LRD', symbol: '$', name: 'Liberian Dollar', locale: 'en-LR' },
  'MG': { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', locale: 'mg-MG' },
  'MW': { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', locale: 'en-MW' },
  'ML': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-ML' },
  'MR': { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', locale: 'ar-MR' },
  'MU': { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', locale: 'en-MU' },
  'MZ': { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', locale: 'pt-MZ' },
  'NA': { code: 'NAD', symbol: '$', name: 'Namibian Dollar', locale: 'en-NA' },
  'NE': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-NE' },
  'RW': { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', locale: 'rw-RW' },
  'ST': { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', locale: 'pt-ST' },
  'SN': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-SN' },
  'SC': { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee', locale: 'en-SC' },
  'SL': { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', locale: 'en-SL' },
  'SO': { code: 'SOS', symbol: 'S', name: 'Somali Shilling', locale: 'so-SO' },
  'SS': { code: 'SSP', symbol: '£', name: 'South Sudanese Pound', locale: 'en-SS' },
  'SD': { code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound', locale: 'ar-SD' },
  'TZ': { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', locale: 'sw-TZ' },
  'TG': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-TG' },
  'UG': { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', locale: 'en-UG' },
  'ZM': { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', locale: 'en-ZM' },
  'ZW': { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar', locale: 'en-ZW' },
  'BI': { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', locale: 'fr-BI' },
  'BJ': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-BJ' },
  'BF': { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', locale: 'fr-BF' },
  'CM': { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', locale: 'fr-CM' },
  'CX': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-CX' },

  // Europe
  'GB': { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
  'DE': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-DE' },
  'FR': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'fr-FR' },
  'IT': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'it-IT' },
  'ES': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'es-ES' },
  'NL': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'nl-NL' },
  'BE': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'nl-BE' },
  'CH': { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', locale: 'de-CH' },
  'AT': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-AT' },
  'SE': { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', locale: 'sv-SE' },
  'NO': { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', locale: 'nb-NO' },
  'DK': { code: 'DKK', symbol: 'kr', name: 'Danish Krone', locale: 'da-DK' },
  'FI': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'fi-FI' },
  'IE': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'en-IE' },
  'PT': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'pt-PT' },
  'PL': { code: 'PLN', symbol: 'zł', name: 'Polish Złoty', locale: 'pl-PL' },
  'CZ': { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', locale: 'cs-CZ' },
  'HU': { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', locale: 'hu-HU' },
  'RO': { code: 'RON', symbol: 'lei', name: 'Romanian Leu', locale: 'ro-RO' },
  'BG': { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', locale: 'bg-BG' },
  'GR': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'el-GR' },
  'HR': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'hr-HR' },
  'SI': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'sl-SI' },
  'SK': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'sk-SK' },
  'EE': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'et-EE' },
  'LV': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'lv-LV' },
  'LT': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'lt-LT' },
  'LU': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'lb-LU' },
  'MT': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'mt-MT' },
  'CY': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'el-CY' },
  'AD': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'ca-AD' },
  'AL': { code: 'ALL', symbol: 'L', name: 'Albanian Lek', locale: 'sq-AL' },
  'AM': { code: 'AMD', symbol: '֏', name: 'Armenian Dram', locale: 'hy-AM' },
  'AZ': { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', locale: 'az-AZ' },
  'BY': { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', locale: 'be-BY' },
  'BA': { code: 'BAM', symbol: 'KM', name: 'Bosnia Mark', locale: 'bs-BA' },
  'GE': { code: 'GEL', symbol: '₾', name: 'Georgian Lari', locale: 'ka-GE' },
  'IS': { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', locale: 'is-IS' },
  'LI': { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc', locale: 'de-LI' },
  'MC': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'fr-MC' },
  'MD': { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', locale: 'ro-MD' },
  'ME': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'sr-ME' },
  'MK': { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', locale: 'mk-MK' },
  'RS': { code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar', locale: 'sr-RS' },
  'SM': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'it-SM' },
  'UA': { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', locale: 'uk-UA' },
  'VA': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'it-VA' },
  'XK': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'sq-XK' },

  // North America
  'US': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' },
  'CA': { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', locale: 'en-CA' },
  'MX': { code: 'MXN', symbol: '$', name: 'Mexican Peso', locale: 'es-MX' },
  'GT': { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', locale: 'es-GT' },
  'BZ': { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', locale: 'en-BZ' },
  'SV': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'es-SV' },
  'HN': { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', locale: 'es-HN' },
  'NI': { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', locale: 'es-NI' },
  'CR': { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', locale: 'es-CR' },
  'PA': { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', locale: 'es-PA' },
  'CU': { code: 'CUP', symbol: '₱', name: 'Cuban Peso', locale: 'es-CU' },
  'DO': { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', locale: 'es-DO' },
  'HT': { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', locale: 'ht-HT' },
  'JM': { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', locale: 'en-JM' },
  'TT': { code: 'TTD', symbol: 'TT$', name: 'Trinidad Dollar', locale: 'en-TT' },
  'BS': { code: 'BSD', symbol: '$', name: 'Bahamian Dollar', locale: 'en-BS' },
  'BB': { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', locale: 'en-BB' },
  'LC': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-LC' },
  'VC': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-VC' },
  'AG': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-AG' },
  'KN': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-KN' },
  'DM': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-DM' },
  'GD': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-GD' },
  'GL': { code: 'DKK', symbol: 'kr', name: 'Danish Krone', locale: 'kl-GL' },
  'PM': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'fr-PM' },
  'MS': { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', locale: 'en-MS' },

  // Central America
  'BQ': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'nl-BQ' },
  'CW': { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', locale: 'nl-CW' },
  'SX': { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', locale: 'nl-SX' },
  'NI': { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', locale: 'es-NI' },

  // Australia & Oceania
  'AU': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-AU' },
  'NZ': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-NZ' },
  'FJ': { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', locale: 'en-FJ' },
  'PG': { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', locale: 'en-PG' },
  'SB': { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', locale: 'en-SB' },
  'VU': { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', locale: 'bi-VU' },
  'WS': { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', locale: 'sm-WS' },
  'TO': { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', locale: 'to-TO' },
  'TV': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-TV' },
  'KI': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-KI' },
  'MH': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-MH' },
  'FM': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-FM' },
  'PW': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-PW' },
  'NR': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-NR' },
  'NU': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-NU' },
  'CK': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-CK' },
  'PF': { code: 'XPF', symbol: 'F', name: 'CFP Franc', locale: 'fr-PF' },
  'PN': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-PN' },
  'WF': { code: 'XPF', symbol: 'F', name: 'CFP Franc', locale: 'fr-WF' },
  'AS': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-AS' },
  'GU': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-GU' },
  'MH': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-MH' },
  'MP': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-MP' },
  'UM': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-UM' },
  'VU': { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', locale: 'bi-VU' },

  // Asia
  'IN': { code: 'INR', symbol: '₹', name: 'Indian Rupee', locale: 'en-IN' },
  'JP': { code: 'JPY', symbol: '¥', name: 'Japanese Yen', locale: 'ja-JP' },
  'CN': { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', locale: 'zh-CN' },
  'KR': { code: 'KRW', symbol: '₩', name: 'South Korean Won', locale: 'ko-KR' },
  'SG': { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', locale: 'en-SG' },
  'TH': { code: 'THB', symbol: '฿', name: 'Thai Baht', locale: 'th-TH' },
  'MY': { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', locale: 'ms-MY' },
  'ID': { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', locale: 'id-ID' },
  'PH': { code: 'PHP', symbol: '₱', name: 'Philippine Peso', locale: 'en-PH' },
  'VN': { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', locale: 'vi-VN' },
  'TW': { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', locale: 'zh-TW' },
  'HK': { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', locale: 'zh-HK' },
  'BD': { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', locale: 'bn-BD' },
  'PK': { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', locale: 'en-PK' },
  'LK': { code: 'LKR', symbol: 'රු', name: 'Sri Lankan Rupee', locale: 'si-LK' },
  'NP': { code: 'NPR', symbol: 'रू', name: 'Nepalese Rupee', locale: 'ne-NP' },
  'MM': { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', locale: 'my-MM' },
  'KH': { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', locale: 'km-KH' },
  'LA': { code: 'LAK', symbol: '₭', name: 'Laotian Kip', locale: 'lo-LA' },
  'MN': { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', locale: 'mn-MN' },
  'BN': { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', locale: 'ms-BN' },
  'TL': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'pt-TL' },
  'BT': { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', locale: 'dz-BT' },
  'MV': { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', locale: 'dv-MV' },
  'AF': { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', locale: 'ps-AF' },
  'KP': { code: 'KPW', symbol: '₩', name: 'North Korean Won', locale: 'ko-KP' },
  'KZ': { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', locale: 'kk-KZ' },
  'KG': { code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som', locale: 'ky-KG' },
  'TJ': { code: 'TJS', symbol: 'ЪМ', name: 'Tajikistani Somoni', locale: 'tg-TJ' },
  'TM': { code: 'TMT', symbol: 'm', name: 'Turkmenistan Manat', locale: 'tk-TM' },
  'UZ': { code: 'UZS', symbol: 'so\'m', name: 'Uzbekistan Som', locale: 'uz-UZ' },
  'MO': { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', locale: 'zh-MO' },
  'IO': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-IO' },

  // South America
  'BR': { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', locale: 'pt-BR' },
  'AR': { code: 'ARS', symbol: '$', name: 'Argentine Peso', locale: 'es-AR' },
  'CO': { code: 'COP', symbol: '$', name: 'Colombian Peso', locale: 'es-CO' },
  'PE': { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', locale: 'es-PE' },
  'VE': { code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar', locale: 'es-VE' },
  'CL': { code: 'CLP', symbol: '$', name: 'Chilean Peso', locale: 'es-CL' },
  'EC': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'es-EC' },
  'BO': { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', locale: 'es-BO' },
  'UY': { code: 'UYU', symbol: '$', name: 'Uruguayan Peso', locale: 'es-UY' },
  'GY': { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', locale: 'en-GY' },
  'SR': { code: 'SRD', symbol: '$', name: 'Surinamese Dollar', locale: 'nl-SR' },
  'PY': { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', locale: 'es-PY' },
  'FK': { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound', locale: 'en-FK' },
  'GF': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'fr-GF' },

  // Middle East
  'SA': { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal', locale: 'ar-SA' },
  'AE': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', locale: 'ar-AE' },
  'QA': { code: 'QAR', symbol: '﷼', name: 'Qatari Riyal', locale: 'ar-QA' },
  'KW': { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', locale: 'ar-KW' },
  'BH': { code: 'BHD', symbol: 'د.ب', name: 'Bahraini Dinar', locale: 'ar-BH' },
  'OM': { code: 'OMR', symbol: '﷼', name: 'Omani Rial', locale: 'ar-OM' },
  'YE': { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', locale: 'ar-YE' },
  'IQ': { code: 'IQD', symbol: 'د.ع', name: 'Iraqi Dinar', locale: 'ar-IQ' },
  'JO': { code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar', locale: 'ar-JO' },
  'LB': { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound', locale: 'ar-LB' },
  'SY': { code: 'SYP', symbol: '£', name: 'Syrian Pound', locale: 'ar-SY' },
  'TR': { code: 'TRY', symbol: '₺', name: 'Turkish Lira', locale: 'tr-TR' },
  'CY': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'el-CY' },
  'IL': { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', locale: 'he-IL' },
  'PS': { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', locale: 'ar-PS' },

  // Antarctica & Special Territories
  'AQ': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-AQ' },
  'AX': { code: 'EUR', symbol: '€', name: 'Euro', locale: 'sv-AX' },
  'BV': { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', locale: 'no-BV' },
  'CC': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-CC' },
  'CX': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-CX' },
  'HM': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-HM' },
  'NF': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-NF' },
  'NU': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-NU' },
  'SH': { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', locale: 'en-SH' },
  'SJ': { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', locale: 'no-SJ' },
  'GS': { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GS' },
  'TK': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-TK' },
  'PN': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', locale: 'en-PN' },

  // Default fallback for any unmapped countries
  'DEFAULT': { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' }
};

/**
 * Gets currency info for a specific country code
 * Falls back to USD if country not found
 */
export function getCurrencyForCountry(countryCode) {
  const upperCode = countryCode ? countryCode.toUpperCase() : 'US';
  return COUNTRY_CURRENCY_MAP[upperCode] || COUNTRY_CURRENCY_MAP.DEFAULT;
}

/**
 * Gets currency symbol for a country code
 */
export function getCurrencySymbolForCountry(countryCode) {
  const currencyInfo = getCurrencyForCountry(countryCode);
  return currencyInfo.symbol;
}

/**
 * Gets currency code for a country code
 */
export function getCurrencyCodeForCountry(countryCode) {
  const currencyInfo = getCurrencyForCountry(countryCode);
  return currencyInfo.code;
}